# Generated by Django 3.2.6 on 2021-08-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciperecommend', '0002_auto_20210814_1300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dishhistory',
            old_name='proba',
            new_name='i_p_proba',
        ),
        migrations.RenameField(
            model_name='dishhistory',
            old_name='result',
            new_name='i_p_result',
        ),
        migrations.AddField(
            model_name='dishhistory',
            name='nutrition_proba',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dishhistory',
            name='nutrition_result',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
