# Generated by Django 3.2.6 on 2021-08-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciperecommend', '0003_auto_20210814_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishhistory',
            name='cover_amt',
            field=models.IntegerField(default=2, verbose_name='材料〜人前'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dishhistory',
            name='sim_dish_ip',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dishhistory',
            name='sim_dish_ntr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
