# Generated by Django 3.2.6 on 2021-08-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciperecommend', '0005_auto_20210816_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishmaster',
            name='cluster',
            field=models.IntegerField(null=True, verbose_name='分類'),
        ),
    ]
