# Generated by Django 3.2.6 on 2021-08-19 05:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciperecommend', '0006_dishmaster_cluster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishmaster',
            name='cluster',
        ),
        migrations.AddField(
            model_name='dishmaster',
            name='cluster_ip',
            field=models.IntegerField(null=True, verbose_name='分類:材料・工程'),
        ),
        migrations.AddField(
            model_name='dishmaster',
            name='cluster_ntr',
            field=models.IntegerField(null=True, verbose_name='分類:栄養'),
        ),
        migrations.AddField(
            model_name='dishmaster',
            name='sim_dish_ip',
            field=models.TextField(null=True, verbose_name='似ている料理:材料・工程'),
        ),
        migrations.AddField(
            model_name='dishmaster',
            name='sim_dish_ntr',
            field=models.TextField(null=True, verbose_name='似ている料理:栄養'),
        ),
        migrations.AlterField(
            model_name='dishhistory',
            name='registered_date',
            field=models.DateField(default=datetime.date(2021, 8, 19)),
        ),
        migrations.AlterField(
            model_name='dishmaster',
            name='registered_date',
            field=models.DateField(default=datetime.date(2021, 8, 19)),
        ),
    ]
