# Generated by Django 3.2.6 on 2021-08-20 01:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciperecommend', '0007_auto_20210819_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietaryReferenceIntake',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('age_range', models.IntegerField(choices=[(1, '18～29歳'), (2, '30歳～49歳'), (3, '50歳～64歳')], default=0, verbose_name='年齢区分')),
                ('gender', models.IntegerField(choices=[(1, '男性'), (2, '女性')], default=0, verbose_name='性別')),
                ('energy', models.IntegerField(verbose_name='エネルギー')),
                ('protein', models.FloatField(verbose_name='タンパク質')),
                ('fat', models.FloatField(verbose_name='脂質')),
                ('calcium', models.IntegerField(verbose_name='カルシウム')),
                ('iron', models.FloatField(verbose_name='鉄分')),
                ('vitamin_a', models.IntegerField(verbose_name='ビタミンA')),
                ('vitamin_b1', models.FloatField(verbose_name='ビタミンB1')),
                ('vitamin_b2', models.FloatField(verbose_name='ビタミンB2')),
                ('vitamin_c', models.IntegerField(verbose_name='ビタミンC')),
                ('registered_date', models.DateField(default=datetime.date(2021, 8, 20))),
            ],
        ),
        migrations.AlterField(
            model_name='dishhistory',
            name='registered_date',
            field=models.DateField(default=datetime.date(2021, 8, 20)),
        ),
        migrations.AlterField(
            model_name='dishmaster',
            name='registered_date',
            field=models.DateField(default=datetime.date(2021, 8, 20)),
        ),
    ]
