# Generated by Django 3.2.6 on 2021-08-29 04:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciperecommend', '0009_auto_20210824_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietaryreferenceintake',
            name='registered_date',
            field=models.DateField(default=datetime.date(2021, 8, 29)),
        ),
        migrations.AlterField(
            model_name='dishhistory',
            name='registered_date',
            field=models.DateField(default=datetime.date(2021, 8, 29)),
        ),
        migrations.AlterField(
            model_name='dishmaster',
            name='registered_date',
            field=models.DateField(default=datetime.date(2021, 8, 29)),
        ),
    ]
