# Generated by Django 3.2.6 on 2021-09-04 00:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciperecommend', '0010_auto_20210829_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishmaster',
            name='cover_amt',
        ),
        migrations.AddField(
            model_name='dishmaster',
            name='carbohydrate',
            field=models.FloatField(default=0, verbose_name='炭水化物'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dishmaster',
            name='recommend_dish',
            field=models.TextField(null=True, verbose_name='おすすめの組み合わせ'),
        ),
        migrations.AlterField(
            model_name='dietaryreferenceintake',
            name='registered_date',
            field=models.DateField(default=datetime.date(2021, 9, 4)),
        ),
        migrations.AlterField(
            model_name='dishhistory',
            name='registered_date',
            field=models.DateField(default=datetime.date(2021, 9, 4)),
        ),
        migrations.AlterField(
            model_name='dishmaster',
            name='registered_date',
            field=models.DateField(default=datetime.date(2021, 9, 4)),
        ),
    ]
