# Generated by Django 3.2.6 on 2021-09-04 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciperecommend', '0011_auto_20210904_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishmaster',
            name='calcium',
            field=models.IntegerField(null=True, verbose_name='カルシウム'),
        ),
        migrations.AlterField(
            model_name='dishmaster',
            name='carbohydrate',
            field=models.FloatField(null=True, verbose_name='炭水化物'),
        ),
        migrations.AlterField(
            model_name='dishmaster',
            name='energy',
            field=models.IntegerField(null=True, verbose_name='エネルギー'),
        ),
        migrations.AlterField(
            model_name='dishmaster',
            name='fat',
            field=models.FloatField(null=True, verbose_name='脂質'),
        ),
        migrations.AlterField(
            model_name='dishmaster',
            name='ingredient',
            field=models.TextField(null=True, verbose_name='材料'),
        ),
        migrations.AlterField(
            model_name='dishmaster',
            name='iron',
            field=models.FloatField(null=True, verbose_name='鉄分'),
        ),
        migrations.AlterField(
            model_name='dishmaster',
            name='process',
            field=models.TextField(null=True, verbose_name='調理工程'),
        ),
        migrations.AlterField(
            model_name='dishmaster',
            name='protein',
            field=models.FloatField(null=True, verbose_name='タンパク質'),
        ),
        migrations.AlterField(
            model_name='dishmaster',
            name='vitamin_a',
            field=models.IntegerField(null=True, verbose_name='ビタミンA'),
        ),
        migrations.AlterField(
            model_name='dishmaster',
            name='vitamin_b1',
            field=models.FloatField(null=True, verbose_name='ビタミンB1'),
        ),
        migrations.AlterField(
            model_name='dishmaster',
            name='vitamin_b2',
            field=models.FloatField(null=True, verbose_name='ビタミンB2'),
        ),
        migrations.AlterField(
            model_name='dishmaster',
            name='vitamin_c',
            field=models.IntegerField(null=True, verbose_name='ビタミンC'),
        ),
    ]
