# Generated by Django 3.2.6 on 2021-09-04 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciperecommend', '0012_auto_20210904_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishmaster',
            name='calcium',
            field=models.FloatField(null=True, verbose_name='カルシウム'),
        ),
        migrations.AlterField(
            model_name='dishmaster',
            name='cluster_ip',
            field=models.FloatField(null=True, verbose_name='分類:材料・工程'),
        ),
        migrations.AlterField(
            model_name='dishmaster',
            name='cluster_ntr',
            field=models.FloatField(null=True, verbose_name='分類:栄養'),
        ),
        migrations.AlterField(
            model_name='dishmaster',
            name='vitamin_a',
            field=models.FloatField(null=True, verbose_name='ビタミンA'),
        ),
        migrations.AlterField(
            model_name='dishmaster',
            name='vitamin_c',
            field=models.FloatField(null=True, verbose_name='ビタミンC'),
        ),
    ]
